version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: gaza
      POSTGRES_PASSWORD: gaza123
      POSTGRES_DB: gaza
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gaza"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: ./api
    ports:
      - "3001:3001"
    environment:
      PORT: 3001
      DATABASE_URL: postgresql://gaza:gaza123@postgres:5432/gaza?schema=public
      JWT_SECRET: ${JWT_SECRET:-your-secret-key-change-in-production}
      NODE_ENV: development
      CORS_ORIGIN: http://localhost:3000
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./api:/app
      - /app/node_modules
    command: sh -c "npx prisma migrate deploy && npm start"

  web:
    build: ./web
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3001
      NODE_ENV: development
    depends_on:
      - api
    volumes:
      - ./web:/app
      - /app/node_modules
      - /app/.next

  mcp:
    build: ./mcp
    environment:
      API_URL: http://api:3001
      REDIS_URL: redis://redis:6379
    depends_on:
      - api
      - redis
    volumes:
      - ./mcp:/app
      - /app/node_modules

volumes:
  postgres_data:
  redis_data:
